---
services:
  media-utilities:
    image: media-utilities:latest
    container_name: media-utilities
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Chicago
    volumes:
      - /docker/media-utilities/config:/config
      - /docker/media-utilities/logs:/logs
    restart: unless-stopped